// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: coupon.proto

package coupon_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CouponsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*CouponResponse      `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponsListResponse) Reset() {
	*x = CouponsListResponse{}
	mi := &file_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponsListResponse) ProtoMessage() {}

func (x *CouponsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponsListResponse.ProtoReflect.Descriptor instead.
func (*CouponsListResponse) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *CouponsListResponse) GetCoupons() []*CouponResponse {
	if x != nil {
		return x.Coupons
	}
	return nil
}

type CouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponResponse) Reset() {
	*x = CouponResponse{}
	mi := &file_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponResponse) ProtoMessage() {}

func (x *CouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponResponse.ProtoReflect.Descriptor instead.
func (*CouponResponse) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *CouponResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_coupon_proto protoreflect.FileDescriptor

const file_coupon_proto_rawDesc = "" +
	"\n" +
	"\fcoupon.proto\x12\x06coupon\x1a\x1bgoogle/protobuf/empty.proto\"G\n" +
	"\x13CouponsListResponse\x120\n" +
	"\acoupons\x18\x01 \x03(\v2\x16.coupon.CouponResponseR\acoupons\"$\n" +
	"\x0eCouponResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code2M\n" +
	"\x06Coupon\x12C\n" +
	"\n" +
	"GetCoupons\x12\x16.google.protobuf.Empty\x1a\x1b.coupon.CouponsListResponse\"\x00B;Z9github.com/israelmiranda/go-samples/examples/coupon-protob\x06proto3"

var (
	file_coupon_proto_rawDescOnce sync.Once
	file_coupon_proto_rawDescData []byte
)

func file_coupon_proto_rawDescGZIP() []byte {
	file_coupon_proto_rawDescOnce.Do(func() {
		file_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)))
	})
	return file_coupon_proto_rawDescData
}

var file_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coupon_proto_goTypes = []any{
	(*CouponsListResponse)(nil), // 0: coupon.CouponsListResponse
	(*CouponResponse)(nil),      // 1: coupon.CouponResponse
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_coupon_proto_depIdxs = []int32{
	1, // 0: coupon.CouponsListResponse.coupons:type_name -> coupon.CouponResponse
	2, // 1: coupon.Coupon.GetCoupons:input_type -> google.protobuf.Empty
	0, // 2: coupon.Coupon.GetCoupons:output_type -> coupon.CouponsListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coupon_proto_init() }
func file_coupon_proto_init() {
	if File_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_proto_goTypes,
		DependencyIndexes: file_coupon_proto_depIdxs,
		MessageInfos:      file_coupon_proto_msgTypes,
	}.Build()
	File_coupon_proto = out.File
	file_coupon_proto_goTypes = nil
	file_coupon_proto_depIdxs = nil
}
