// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/israelmiranda/go-samples/examples/di/installments"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func NewUseCase(db *sql.DB) *installments.InstallmentUseCase {
	installmentRepository := installments.NewInstallmentRepository(db)
	installmentUseCase := installments.NewIntallmentUseCase(installmentRepository)
	return installmentUseCase
}

// wire.go:

var setRepositoryDependency = wire.NewSet(installments.NewInstallmentRepository, wire.Bind(
	new(installments.InstallmentRepositoryInterface),
	new(*installments.InstallmentRepository),
),
)
